version: '3.8'

services:
  redis:
    container_name: 'redis-golang'
    image: redis:alpine
    ports:
      - '6379:6379'

  go-service:
    container_name: Golang
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5001:5001
    # Important to bind/mount your codebase dir to /app dir for live reload

    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-gorm
    ports:
      - '3307:3306'
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=123123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
