version: '3.8'

services:
  redis:
    container_name: 'redis-golang'
    image: redis:alpine
    ports:
      - '6379:6379'

  go-service:
    container_name: Golang
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5001:5001
    # Important to bind/mount your codebase dir to /app dir for live reload

    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local
